SELECT COUNT(DATE_FORMAT(Order_Date,'%M %Y')) AS COUNT_DATE , DATE_FORMAT(Order_Date,'%M %Y') AS ORD_DATE
FROM orders_dimen
WHERE Order_Priority = 'CRITICAL'
GROUP BY ORD_DATE
ORDER BY COUNT_DATE DESC LIMIT 1;
